#!/usr/bin/env python

import os
import sys


def print_tree(dirname, indent, summary=False):
    filenames = os.listdir(dirname)
    filenames.sort()
    if summary:
        dirnames = []
        subfilenames = []
        for filename in filenames:
            if filename.startswith('.'):
                continue
            fullname = os.path.join(dirname, filename)
            if os.path.isdir(fullname):
                dirnames.append(filename)
            else:
                subfilenames.append(filename)
        filenames = dirnames
        if subfilenames:
            file_string = ' '.join(subfilenames)
            if len(indent + file_string) > 75:
                file_string = file_string[:75 - len(indent)] + '...'
            filenames.append(file_string)
    for filename in filenames:
        if filename.startswith('.'):
            continue
        fullname = os.path.join(dirname, filename)
        if os.path.isdir(fullname):
            print indent + filename + '/'
            print_tree(fullname, indent + '    ', summary=summary)
        else:
            print indent + filename


def main(args):
    summary = True
    while args and args[0].startswith('-'):
        opt = args.pop(0)
        if opt in ('-f', '--full'):
            summary = False
        else:
            raise ValueError("Unknown command-line option '%s'" % opt)
    if not args:
        args = ['.']
    print_tree(args[0], '', summary=summary)


if __name__ == '__main__':
    main(sys.argv[1:])
