#!/usr/bin/env python

# Written by Chris Pressey of Cat's Eye Technologies.
# This work is in the public domain; see UNLICENSE for more information.

import os
import sys


def print_tree(dirname, indent, summary=False, maxwidth=75):
    filenames = os.listdir(dirname)
    filenames.sort()
    if summary:
        dirnames = []
        subfilenames = []
        for filename in filenames:
            if filename.startswith('.'):
                continue
            fullname = os.path.join(dirname, filename)
            if os.path.islink(fullname):
                subfilenames.append(filename)
            elif os.path.isdir(fullname):
                dirnames.append(filename)
            else:
                subfilenames.append(filename)
        filenames = dirnames
        if subfilenames:
            file_string = ' '.join(subfilenames)
            if len(indent + file_string) > maxwidth:
                file_string = file_string[:(maxwidth - 4) - len(indent)] + '...'
            filenames.append(file_string)
    for filename in filenames:
        if filename.startswith('.'):
            continue
        fullname = os.path.join(dirname, filename)
        if os.path.isdir(fullname):
            print indent + filename + '/'
            print_tree(fullname, indent + '    ', summary=summary,
                       maxwidth=maxwidth)
        else:
            print indent + filename


def main(args):
    summary = True
    maxwidth = 75
    try:
        import subprocess
        with open('/dev/tty') as tty:
            height, width = subprocess.check_output(['stty', 'size'], stdin=tty).split()
        maxwidth = int(width)
    except Exception as e:
        pass
    while args and args[0].startswith('-'):
        opt = args.pop(0)
        if opt in ('-f', '--full'):
            summary = False
        elif opt in ('-w', '--max-width'):
            val = args.pop(0)
            maxwidth = int(val)
            if maxwidth <= 0:
                raise ValueError("Illegal --max-width '%s'" % val)
        else:
            raise ValueError("Unknown command-line option '%s'" % opt)
    if not args:
        args = ['.']
    print_tree(args[0], '', summary=summary, maxwidth=maxwidth)


if __name__ == '__main__':
    main(sys.argv[1:])
